# Generated by Django 3.0.3 on 2020-08-24 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imageboard.models.image


class Migration(migrations.Migration):

    replaces = [('imageboard', '0001_initial'), ('imageboard', '0002_auto_20180810_0800'), ('imageboard', '0003_remove_thread_last_post_hid'), ('imageboard', '0004_board_custom_style'), ('imageboard', '0005_auto_20181010_1254'), ('imageboard', '0006_auto_20181225_1051'), ('imageboard', '0007_auto_20190111_1136'), ('imageboard', '0008_post_session_id'), ('imageboard', '0009_auto_20190129_1529'), ('imageboard', '0010_auto_20190204_1314'), ('imageboard', '0011_auto_20190208_1149'), ('imageboard', '0012_auto_20190208_1153'), ('imageboard', '0013_auto_20200211_2008'), ('imageboard', '0014_auto_20200211_2009'), ('imageboard', '0015_auto_20200211_2010'), ('imageboard', '0016_contentblock'), ('imageboard', '0017_auto_20200814_1026'), ('imageboard', '0018_auto_20200824_1851')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(db_index=True, max_length=8, verbose_name='HID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Short board description', max_length=256, verbose_name='Description')),
                ('rules', models.TextField(blank=True, help_text='Board rules will be displayed next to posting form.', verbose_name='Rules')),
                ('default_username', models.CharField(help_text="Default username will be saved, if post's author field was empty.", max_length=32, verbose_name='Default username')),
                ('default_max_posts_num', models.IntegerField(default=128, help_text="Maximum number of posts for new threads by default. Can be overridden in thread's properties.", verbose_name='Default maximum posts number')),
                ('is_hidden', models.BooleanField(default=False, help_text='Is this board hidden from boards list. Can still be accessed by direct URL.', verbose_name='Is hidden')),
                ('is_locked', models.BooleanField(default=False, help_text="New posts and threads can't be created on locked board.", verbose_name='Is locked')),
                ('is_deleted', models.BooleanField(default=False, help_text="Boards is removed from boards list and can't be accessed by direct URL.", verbose_name='Is deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('last_post_hid', models.IntegerField(null=True, verbose_name='Last post HID')),
                ('custom_style', models.TextField(blank=True, help_text="Custom CSS that would be applied only on this board's pages", verbose_name='Custom style')),
                ('max_threads_num', models.IntegerField(default=100, help_text='Maximum number of threads on this boards. When reaching this level older threads will be deleted.', verbose_name='Maximum threads number')),
                ('posts_per_thread_per_page', models.IntegerField(default=5, help_text="Number of thread's posts visible on board's pages, not counting OP post.", verbose_name='Posts per thread per page')),
                ('threads_per_page', models.IntegerField(default=10, help_text="Number of threads on board's page", verbose_name='Threads per page')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
                'ordering': ['hid'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField(db_index=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('text', models.TextField(blank=True, max_length=2048)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('author', models.CharField(blank=True, max_length=32)),
                ('email', models.CharField(blank=True, max_length=32)),
                ('password', models.CharField(blank=True, max_length=16)),
                ('is_op', models.BooleanField(editable=False)),
                ('user_was_warned', models.BooleanField(default=False)),
                ('user_was_banned', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.CharField(db_index=True, editable=False, max_length=16)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('replies', models.ManyToManyField(db_index=True, editable=False, to='imageboard.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField(db_index=True, editable=False, verbose_name='HID')),
                ('is_sticky', models.BooleanField(db_index=True, default=False, verbose_name='Is sticky')),
                ('is_locked', models.BooleanField(db_index=True, default=False, verbose_name='Is locked')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is deleted')),
                ('max_posts_num', models.IntegerField(verbose_name='Maximum posts number')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='imageboard.Board', verbose_name='Board')),
                ('op', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='imageboard.Post')),
            ],
            options={
                'unique_together': {('board', 'hid')},
                'verbose_name': 'Thread',
                'verbose_name_plural': 'Threads',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='imageboard.Thread'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('thread', 'hid')},
        ),
        migrations.RemoveField(
            model_name='post',
            name='replies',
        ),
        migrations.AddField(
            model_name='post',
            name='refs',
            field=models.ManyToManyField(db_index=True, editable=False, to='imageboard.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='session_id',
            field=models.CharField(db_index=True, default='00000000000000000000000000000000', editable=False, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=32, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.CharField(blank=True, max_length=32, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hid',
            field=models.IntegerField(db_index=True, editable=False, verbose_name='HID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ip_address',
            field=models.CharField(db_index=True, editable=False, max_length=16, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is deleted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_op',
            field=models.BooleanField(editable=False, verbose_name='Is OP'),
        ),
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(blank=True, max_length=16, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='post',
            name='refs',
            field=models.ManyToManyField(db_index=True, editable=False, to='imageboard.Post', verbose_name='Refs'),
        ),
        migrations.AlterField(
            model_name='post',
            name='session_id',
            field=models.CharField(db_index=True, editable=False, max_length=32, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='imageboard.Thread', verbose_name='Thread'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=64, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_was_banned',
            field=models.BooleanField(default=False, verbose_name='User was banned'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_was_warned',
            field=models.BooleanField(default=False, verbose_name='User was warned'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='op',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='imageboard.Post', verbose_name='OP'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at'),
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Thread', 'verbose_name_plural': 'Threads'},
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(editable=False, max_length=128, verbose_name='Original name')),
                ('mimetype', models.CharField(editable=False, max_length=16, verbose_name='MIME type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('size', models.IntegerField(editable=False, verbose_name='Size')),
                ('width', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Width')),
                ('height', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Height')),
                ('is_spoiler', models.BooleanField(default=False, verbose_name='Is spoiler')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is deleted')),
                ('checksum', models.CharField(blank=True, editable=False, max_length=32, verbose_name='Checksum')),
                ('thumb_width', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Thumb width')),
                ('thumb_height', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Thumb height')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='imageboard.Post', verbose_name='Post')),
                ('file', models.ImageField(blank=True, editable=False, height_field='height', upload_to=imageboard.models.image.make_file_upload_path, verbose_name='Image', width_field='width')),
                ('thumb_file', models.ImageField(blank=True, editable=False, height_field='thumb_height', upload_to=imageboard.models.image.make_thumb_file_upload_path, verbose_name='Thumb', width_field='thumb_width')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='HID')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Content block',
                'verbose_name_plural': 'Content blocks',
            },
        ),
    ]
