# Generated by Django 3.0.3 on 2021-04-28 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imageboard.models.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(db_index=True, max_length=8, verbose_name='HID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Short board description', max_length=256, verbose_name='Description')),
                ('rules', models.TextField(blank=True, help_text='Board rules will be displayed next to posting form.', verbose_name='Rules')),
                ('custom_style', models.TextField(blank=True, help_text="Custom CSS that would be applied only on this board's pages", verbose_name='Custom style')),
                ('default_username', models.CharField(help_text="Default username will be saved, if post's author field was empty.", max_length=32, verbose_name='Default username')),
                ('default_max_posts_num', models.IntegerField(default=128, help_text="Maximum number of posts for new threads by default. Can be overridden in thread's properties.", verbose_name='Default maximum posts number')),
                ('posts_per_thread_per_page', models.IntegerField(default=5, help_text="Number of thread's posts visible on board's pages, not counting OP post.", verbose_name='Posts per thread per page')),
                ('threads_per_page', models.IntegerField(default=10, help_text="Number of threads on board's page", verbose_name='Threads per page')),
                ('max_threads_num', models.IntegerField(default=100, help_text='Maximum number of threads on this boards. When reaching this level older threads will be deleted.', verbose_name='Maximum threads number')),
                ('is_hidden', models.BooleanField(default=False, help_text='Is this board hidden from boards list. Can still be accessed by direct URL.', verbose_name='Is hidden')),
                ('is_locked', models.BooleanField(default=False, help_text="New posts and threads can't be created on locked board.", verbose_name='Is locked')),
                ('is_deleted', models.BooleanField(default=False, help_text="Boards is removed from boards list and can't be accessed by direct URL.", verbose_name='Is deleted')),
                ('last_post_hid', models.IntegerField(null=True, verbose_name='Last post HID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
                'ordering': ['hid'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='HID')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Content block',
                'verbose_name_plural': 'Content blocks',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField(db_index=True, editable=False, verbose_name='HID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('text', models.TextField(blank=True, max_length=2048, verbose_name='Text')),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='Title')),
                ('author', models.CharField(blank=True, max_length=32, verbose_name='Author')),
                ('email', models.CharField(blank=True, max_length=32, verbose_name='E-mail')),
                ('password', models.CharField(blank=True, max_length=16, verbose_name='Password')),
                ('is_op', models.BooleanField(editable=False, verbose_name='Is OP')),
                ('user_was_warned', models.BooleanField(default=False, verbose_name='User was warned')),
                ('user_was_banned', models.BooleanField(default=False, verbose_name='User was banned')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is deleted')),
                ('ip_address', models.CharField(db_index=True, editable=False, max_length=16, verbose_name='IP address')),
                ('session_id', models.CharField(db_index=True, editable=False, max_length=32, verbose_name='Session ID')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('refs', models.ManyToManyField(db_index=True, editable=False, to='imageboard.Post', verbose_name='Refs')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField(db_index=True, editable=False, verbose_name='HID')),
                ('is_sticky', models.BooleanField(db_index=True, default=False, verbose_name='Is sticky')),
                ('is_locked', models.BooleanField(db_index=True, default=False, verbose_name='Is locked')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is deleted')),
                ('max_posts_num', models.IntegerField(verbose_name='Maximum posts number')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='imageboard.Board', verbose_name='Board')),
                ('op', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='imageboard.Post', verbose_name='OP')),
            ],
            options={
                'verbose_name': 'Thread',
                'verbose_name_plural': 'Threads',
                'ordering': ['-updated_at'],
                'unique_together': {('board', 'hid')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='imageboard.Thread', verbose_name='Thread'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, editable=False, height_field='height', upload_to=imageboard.models.image.make_file_upload_path, verbose_name='Image', width_field='width')),
                ('original_name', models.CharField(editable=False, max_length=128, verbose_name='Original name')),
                ('mimetype', models.CharField(editable=False, max_length=16, verbose_name='MIME type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('size', models.IntegerField(editable=False, verbose_name='Size')),
                ('width', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Width')),
                ('height', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Height')),
                ('is_spoiler', models.BooleanField(default=False, verbose_name='Is spoiler')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is deleted')),
                ('checksum', models.CharField(blank=True, editable=False, max_length=32, verbose_name='Checksum')),
                ('thumb_file', models.ImageField(blank=True, editable=False, height_field='thumb_height', upload_to=imageboard.models.image.make_thumb_file_upload_path, verbose_name='Thumb', width_field='thumb_width')),
                ('thumb_width', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Thumb width')),
                ('thumb_height', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Thumb height')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='imageboard.Post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(editable=False, max_length=32, verbose_name='Solution')),
                ('image', models.TextField(editable=False, verbose_name='Encoded image')),
                ('ip_address', models.CharField(db_index=True, editable=False, max_length=16, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('board', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='imageboard.Board', verbose_name='Board')),
                ('thread', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='imageboard.Thread', verbose_name='Thread')),
            ],
            options={
                'verbose_name': 'Captcha',
                'verbose_name_plural': 'Captchas',
            },
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('thread', 'hid')},
        ),
    ]
