# Generated by Django 3.0.3 on 2021-04-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0001_squashed_0018_auto_20200824_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=32, verbose_name='Public ID')),
                ('solution', models.CharField(max_length=32, verbose_name='Solution')),
                ('image', models.TextField(verbose_name='Encoded image')),
            ],
            options={
                'verbose_name': 'Captcha',
                'verbose_name_plural': 'Captchas',
            },
        ),
    ]
