# Generated by Django 3.0.3 on 2021-05-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0002_auto_20210428_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='captcha',
            unique_together={('board', 'thread', 'ip_address')},
        ),
    ]
