# Generated by Django 3.0.3 on 2021-05-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0003_auto_20210508_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='keywords',
            field=models.CharField(blank=True, help_text='Search engine keywords', max_length=256, verbose_name='Keywords'),
        ),
    ]
