# Generated by Django 3.0.1 on 2020-02-11 20:08

from django.db import migrations, models
import imageboard.models.image


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0012_auto_20190208_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, editable=False, height_field='height', upload_to=imageboard.models.image.make_file_upload_path, verbose_name='Image', width_field='width'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumb_file',
            field=models.ImageField(blank=True, editable=False, height_field='thumb_height', upload_to=imageboard.models.image.make_thumb_file_upload_path, verbose_name='Thumb', width_field='thumb_width'),
        ),
    ]
