# Generated by Django 3.0.3 on 2020-08-14 10:25

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0015_auto_20200211_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.TextField(db_index=True, max_length=32, unique=True, verbose_name='HID')),
                ('text', markdownx.models.MarkdownxField(blank=True, verbose_name='Text')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Content block',
                'verbose_name_plural': 'Content blocks',
            },
        ),
    ]
