# Generated by Django 3.0.3 on 2020-08-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0016_contentblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='hid',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='HID'),
        ),
    ]
