# Generated by Django 3.0.3 on 2020-08-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0017_auto_20200814_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='text',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
    ]
