language: python

python:
  - "3.6"

services:
  - postgresql

before_script:
  - cd src
  - ./manage.py create_storage_dirs
  - ./manage.py create_postgresql_script | psql -U postgres -a
  - ./manage.py migrate


script:
  - ./manage.py test
