version: "3.7"

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=hexchan
      - POSTGRES_USER=hexchan
      - POSTGRES_PASSWORD=swordfish

  web:
    build: .
    command: ./docker-command.sh
    volumes:
      - .:/srv/hexchan
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
