version: "3.7"

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=hexchan
      - POSTGRES_USER=hexchan
      - POSTGRES_PASSWORD=swordfish

  web:
    build: .
    command: ./docker-command.sh
    volumes:
      - hexchan_storage:/srv/hexchan/storage
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - hexchan_storage:/srv/hexchan/storage
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  hexchan_storage:
